# Generated by Django 2.2.19 on 2021-03-05 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('inactivce', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('taxid', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='reporttype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('inactivce', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('inactivce', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='sustain.account')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reporttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='sustain.reporttype')),
            ],
        ),
        migrations.CreateModel(
            name='participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('inactivce', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='sustain.account')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='sustain.report')),
            ],
        ),
        migrations.CreateModel(
            name='businesstype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('inactivce', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='accountbusinesstype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('inactivce', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('accountfrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesstypesfrom', to='sustain.account')),
                ('accountto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesstypesto', to='sustain.account')),
                ('businesstype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountbusinesstypes', to='sustain.businesstype')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
