# Generated by Django 2.2.19 on 2021-03-05 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustain', '0002_article_commentreview_commentsextern_commentsintern'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreview',
            name='commentsextern',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='sustain.commentsextern'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentreview',
            name='commentsintern',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='sustain.commentsintern'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentsextern',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='externalcomments', to='sustain.article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentsintern',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='internalcomments', to='sustain.article'),
            preserve_default=False,
        ),
    ]
