# Generated by Django 2.2.19 on 2021-03-05 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustain', '0003_auto_20210305_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreview',
            name='commentsextern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='sustain.commentsextern'),
        ),
        migrations.AlterField(
            model_name='commentreview',
            name='commentsintern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='sustain.commentsintern'),
        ),
    ]
