# Generated by Django 2.2.19 on 2021-03-05 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustain', '0005_account_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='inactivce',
            new_name='inactive',
        ),
        migrations.RenameField(
            model_name='accountbusinesstype',
            old_name='inactivce',
            new_name='inactive',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='inactivce',
            new_name='inactive',
        ),
        migrations.RenameField(
            model_name='businesstype',
            old_name='inactivce',
            new_name='inactive',
        ),
        migrations.RenameField(
            model_name='commentreview',
            old_name='inactivce',
            new_name='inactive',
        ),
        migrations.RenameField(
            model_name='commentsextern',
            old_name='inactivce',
            new_name='inactive',
        ),
        migrations.RenameField(
            model_name='commentsintern',
            old_name='inactivce',
            new_name='inactive',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='inactivce',
            new_name='inactive',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='inactivce',
            new_name='inactive',
        ),
        migrations.RenameField(
            model_name='reporttype',
            old_name='inactivce',
            new_name='inactive',
        ),
    ]
