# Generated by Django 2.2.19 on 2021-03-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustain', '0006_auto_20210305_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/articles/'),
        ),
    ]
